version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: "your_secret_key"
      DATABASE_URL: "postgres://user:password@db:5432/auth_service"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_service
    ports:
      - "5432:5432"
